import psycopg2
import pandas as pd

conn = psycopg2.connect(
    host = '<endpoint>',
    database = '<db_name>',
    user = 'postgres',
    password = '<password>',
    port = '5432'
)

cursor = conn.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT UNIQUE NOT NULL,
    phone_number  TEXT UNIQUE NOT NULL,
    user_type     TEXT NOT NULL CHECK (user_type IN ('rider','driver','both')),
    rating        NUMERIC(2,1) CHECK (rating BETWEEN 0 AND 5),
    created_at    TIMESTAMP DEFAULT NOW()
    );
"""  
)

cursor.execute("""
    INSERT INTO users (user_id, name, email, phone_number, user_type, rating)
    VALUES
    (1, 'Amit Sharma', 'amit@example.com', '9876543210', 'rider', 4.7),
    (2, 'Riya Gupta', 'riya@example.com', '9876543211', 'rider', 4.8),
    (3, 'Karan Mehta', 'karan@example.com', '9876543212', 'driver', 4.5),
    (4, 'Sneha Patil', 'sneha@example.com', '9876543213', 'driver', 4.6),
    (5, 'Rohan Deshmukh', 'rohan@example.com', '9876543214', 'both', 4.7),
    (6, 'Meera Shetty', 'meera@example.com', '9876543215', 'rider', 4.9),
    (7, 'Aditya Verma', 'aditya@example.com', '9876543216', 'driver', 4.4),
    (8, 'Neha Kulkarni', 'neha@example.com', '9876543217', 'rider', 4.2),
    (9, 'Suresh Iyer', 'suresh@example.com', '9876543218', 'driver', 4.8),
    (10,'Pooja Nair', 'pooja@example.com', '9876543219', 'rider', 4.3),
    (11,'Harshit Tiwari', 'harshit@example.com', '9876543220', 'driver', 4.1),
    (12,'Ayesha Khan', 'ayesha@example.com', '9876543221', 'rider', 4.6);
""")

cursor.execute("""
    CREATE TABLE drivers (
    driver_id      INTEGER PRIMARY KEY,
    license_number TEXT UNIQUE NOT NULL,
    vehicle_number TEXT UNIQUE NOT NULL,
    vehicle_model  TEXT NOT NULL,
    background_check_status TEXT CHECK (background_check_status IN ('pending','verified','rejected')),
    onboarded_at   TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (driver_id) REFERENCES users(user_id)
    );
"""  
)

cursor.execute("""
    INSERT INTO drivers (driver_id, license_number, vehicle_number, vehicle_model, background_check_status)
    VALUES
    (3, 'LIC1001', 'MH12AB1234', 'Honda City', 'verified'),
    (4, 'LIC1002', 'MH14XY4321', 'Suzuki Dzire', 'verified'),
    (5, 'LIC1003', 'MH12MN7890', 'Hyundai Creta', 'pending'),
    (7, 'LIC1004', 'MH12PQ4567', 'Toyota Etios', 'verified'),
    (9, 'LIC1005', 'MH12JK9876', 'Maruti WagonR', 'verified'),
    (11,'LIC1006', 'MH14LM6543', 'Hyundai i20', 'pending');
""")

cursor.execute("""
    CREATE TABLE rides (
    ride_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id      INTEGER NOT NULL REFERENCES users(user_id),
    driver_id     INTEGER NOT NULL REFERENCES users(user_id),
    pickup_location TEXT NOT NULL,
    drop_location   TEXT NOT NULL,
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    status          TEXT CHECK (status IN ('requested','ongoing','completed','cancelled')),
    created_at      TIMESTAMP DEFAULT NOW()
);
"""
)

cursor.execute("""
    INSERT INTO rides (ride_id, rider_id, driver_id, pickup_location, drop_location, start_time, end_time, status)
    VALUES
    (1, 2, 3, 'Kothrud', 'Baner', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '1 hour', 'completed'),
    (2, 1, 4, 'Hinjewadi', 'Aundh', NOW() - INTERVAL '1 hour', NULL, 'ongoing'),
    (3, 6, 7, 'Viman Nagar', 'Kharadi', NULL, NULL, 'requested'),
    (4, 10, 9, 'FC Road', 'Swargate', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '2 hours', 'completed'),
    (5, 12, 11, 'Hadapsar', 'Magarpatta', NULL, NULL, 'cancelled'),
    (6, 8, 3, 'Shivaji Nagar', 'Pashan', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '4 hours', 'completed'),
    (7, 5, 9, 'Deccan', 'Camp', NOW() - INTERVAL '7 hours', NOW() - INTERVAL '6 hours', 'completed');
"""
)

cursor.execute("""
CREATE TABLE fares (
    fare_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id       INTEGER UNIQUE NOT NULL REFERENCES rides(ride_id),
    base_fare     NUMERIC(10,2),
    distance_fare NUMERIC(10,2),
    time_fare     NUMERIC(10,2),
    surge_multiplier NUMERIC(4,2),
    total_fare       NUMERIC(10,2)
);""")

cursor.execute("""
    INSERT INTO fares (fare_id, ride_id, base_fare, distance_fare, time_fare, surge_multiplier, total_fare)
    VALUES
    (1, 1, 50, 120, 30, 1.0, 200),
    (2, 4, 70, 90, 25, 1.0, 185),
    (3, 6, 80, 110, 30, 1.1, 242),
    (4, 7, 50, 70, 20, 1.0, 140),
    (5, 2, 60, 100, 20, 1.2, 216); 
""")

cursor.execute("""
    CREATE TABLE payments (
    payment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id        INTEGER UNIQUE NOT NULL REFERENCES rides(ride_id),
    payment_method TEXT CHECK (payment_method IN ('card','upi','wallet','cash')),
    amount         NUMERIC(10,2) NOT NULL,
    status         TEXT CHECK (status IN ('success','failed','refunded')),
    transaction_date TIMESTAMP DEFAULT NOW()
);
""")

cursor.execute("""
    INSERT INTO payments (payment_id, ride_id, payment_method, amount, status)
    VALUES
    (1, 1, 'upi', 200, 'success'),
    (2, 4, 'cash', 185, 'success'),
    (3, 6, 'wallet', 242, 'success'),
    (4, 7, 'upi', 140, 'success'),
    (5, 2, 'card', 216, 'success');
""")

cursor.execute("""
    CREATE TABLE ratings (
    rating_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id       INTEGER NOT NULL REFERENCES rides(ride_id),
    rater_id      INTEGER NOT NULL REFERENCES users(user_id),
    ratee_id      INTEGER NOT NULL REFERENCES users(user_id),
    rating_score  NUMERIC(2,1) CHECK (rating_score BETWEEN 1 AND 5),
    review_text   TEXT,
    created_at    TIMESTAMP DEFAULT NOW()
);
""")

cursor.execute("""
    INSERT INTO ratings (rating_id, ride_id, rater_id, ratee_id, rating_score, review_text)
    VALUES
    (1, 1, 2, 3, 5.0, 'Smooth and professional'),
    (2, 4, 10, 9, 4.5, 'Good ride'),
    (3, 6, 8, 3, 4.0, 'Comfortable experience'),
    (4, 7, 5, 9, 5.0, 'Excellent service');
""")

cursor.execute("""
    CREATE TABLE support_tickets (
    ticket_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(user_id),
    ride_id      INTEGER REFERENCES rides(ride_id),
    issue_type   TEXT NOT NULL,
    description  TEXT NOT NULL,
    status       TEXT CHECK (status IN ('open','in_progress','closed')),
    created_at   TIMESTAMP DEFAULT NOW(),
    resolved_at  TIMESTAMP
);
""")

cursor.execute("""
    INSERT INTO support_tickets (ticket_id, user_id, ride_id, issue_type, description, status)
    VALUES
    (1, 1, 2, 'Payment Issue', 'Amount deducted twice', 'open'),
    (2, 6, NULL, 'App Bug', 'App keeps freezing', 'in_progress'),
    (3, 12, 5, 'Cancellation', 'Driver cancelled without reason', 'open'),
    (4, 8, 6, 'Fare Dispute', 'Fare seems incorrect', 'closed');
""")
cursor.execute("SELECT * FROM support_tickets;")
df = pd.DataFrame(cursor.fetchall(), columns=[col[0] for col in cursor.description])
print(df)

